### ISSUE TITLE
Rename `easytree.list` and `easytree.dict`

### ISSUE THREAD

**Issue by mhmh4** [dschenck/easytree#5]
The classes of `easytree.list` and `easytree.dict` shadows the built-in functions of `list` and `dict`. This can pose a problem such as the example below where one cannot use the built-in `list` or `dict` anymore when using `import-from` statements.

```python
from easytree import list, dict

# need to make an easytree list and dict
a = list()
b = dict()

print(type(a), type(b)) # <class 'easytree.types.list'> <class 'easytree.types.dict'>

# now need to make a regular list and dict
c = list()
d = dict()

print(type(c), type(d)) # <class 'easytree.types.list'> <class 'easytree.types.dict'>
# ^ needed default list and dict, not easytree's
```

To fix this, one possible solution is to capitalize the class names to `easytree.List` and `easytree.Dict`. However, this would then intefere with the typing module's `List` and `Dict`, if that's worth considering.

One other possible solution is to rename them to `easytree.EasyList` or `easytree.EasyDict` or some other variation.

**Comment by dschenck** [comment]
This is intentional and ultimately a design choice.

My recommendation is simply to import easytree (optionally renaming to a shorter name, if reducing verbosity is the intention) and to prefix dict and list instantiation. 

```python
import easytree

data = easytree.dict()

friends = easytree.list()
```

Importing objects from a package is an antipattern in my view, as it obfuscates the use of third-party libraries in source code.

This is same reason we generally `import pandas as pd` rather than `from pandas import DataFrame, Series`
